services:
    engineblock.controller.api.connections:
        class: OpenConext\EngineBlockBundle\Controller\Api\ConnectionsController
        arguments:
            - "@security.authorization_checker"
            - "@engineblock.features"
            - "@engineblock.compat.application"

    engineblock.controller.api.consent:
        class: OpenConext\EngineBlockBundle\Controller\Api\ConsentController
        arguments:
            - "@security.authorization_checker"
            - "@engineblock.features"
            - "@engineblock.service.consent"

    engineblock.controller.api.heartbeat:
        class: OpenConext\EngineBlockBundle\Controller\Api\HeartbeatController

    engineblock.controller.api.metadata:
        class: OpenConext\EngineBlockBundle\Controller\Api\MetadataController
        arguments:
            - "@security.authorization_checker"
            - "@engineblock.features"
            - "@engineblock.service.metadata"
