parameters:
    engineblock.functional_testing.service_registry_data_store.dir:           "%kernel.root_dir%/../tmp/eb-fixtures/janus/"
    engineblock.functional_testing.service_registry_data_store.file:          "%kernel.root_dir%/../tmp/eb-fixtures/janus/entities"
    engineblock.functional_testing.features_data_store.file:                  "%kernel.root_dir%/../tmp/eb-fixtures/features.json"
    engineblock.functional_testing.authentication_loop_guard_data_store.file: "%kernel.root_dir%/../tmp/eb-fixtures/authentication-loop-guard.json"
    engineblock.functional_testing.pdp_data_store.file:                       "%kernel.root_dir%/../tmp/eb-fixtures/policy_decision.json"
    engineblock.functional_testing.attribute_aggregation_data_store.file:     "%kernel.root_dir%/../tmp/eb-fixtures/attribute_aggregation.json"

services:
    engineblock.functional_testing.service.engine_block:
        class: OpenConext\EngineBlockFunctionalTestingBundle\Service\EngineBlock
        arguments:
            - '%engineblock_url%'

    #region Behat Contexts
    engineblock.functional_testing.behat_context.mink:
        class: OpenConext\EngineBlockFunctionalTestingBundle\Features\Context\MinkContext

    engineblock.functional_testing.behat_context.engine_block:
        class: OpenConext\EngineBlockFunctionalTestingBundle\Features\Context\EngineBlockContext
        arguments:
            - '@engineblock.functional_testing.fixture.service_registry'
            - '@engineblock.functional_testing.service.engine_block'
            - '@engineblock.mock_entities.sp_registry'
            - '@engineblock.mock_entities.idp_registry'
            - '%sps_config_url%'
            - '%idps_config_url%'
            - '@engineblock.functional_testing.fixture.features'
            - '@engineblock.functional_testing.fixture.pdp_client'
            - '@engineblock.functional_testing.fixture.authentication_loop_guard'
            - '@engineblock.functional_testing.fixture.attribute_aggregation_client'

    engineblock.functional_testing.behat_context.mock_idp:
        class: OpenConext\EngineBlockFunctionalTestingBundle\Features\Context\MockIdpContext
        arguments:
            - '@engineblock.functional_testing.fixture.service_registry'
            - '@engineblock.functional_testing.service.engine_block'
            - '@engineblock.mock_entities.idp_factory'
            - '@engineblock.mock_entities.idp_registry'
            - '@engineblock.mock_entities.sp_registry'

    engineblock.functional_testing.behat_context.mock_sp:
        class: OpenConext\EngineBlockFunctionalTestingBundle\Features\Context\MockSpContext
        arguments:
            - '@engineblock.functional_testing.fixture.service_registry'
            - '@engineblock.functional_testing.service.engine_block'
            - '@engineblock.mock_entities.sp_factory'
            - '@engineblock.mock_entities.sp_registry'
            - '@engineblock.mock_entities.idp_registry'
    #endregion Behat Contexts

    #region Fixtures
    engineblock.functional_testing.fixture.service_registry:
        class: OpenConext\EngineBlockFunctionalTestingBundle\Fixtures\ServiceRegistryFixture
        arguments:
            - '@engineblock.functional_testing.data_store.service_registry'
            - '%engineblock.functional_testing.service_registry_data_store.dir%'

    engineblock.functional_testing.metadata.repository.fixture_reader:
        class: OpenConext\EngineBlock\Metadata\MetadataRepository\InMemoryMetadataRepository
        factory: ['@engineblock.functional_testing.fixture.service_registry', 'createInMemoryMetadataRepository']

    engineblock.functional_testing.metadata.repository.composite:
        class: OpenConext\EngineBlock\Metadata\MetadataRepository\CompositeMetadataRepository
        arguments:
            - ['@engineblock.functional_testing.metadata.repository.fixture_reader']

    engineblock.functional_testing.fixture.features:
        class: OpenConext\EngineBlockFunctionalTestingBundle\Fixtures\FunctionalTestingFeatureConfiguration
        arguments:
            - '@engineblock.features'
            - '@engineblock.functional_testing.data_store.features'

    engineblock.functional_testing.fixture.pdp_client:
        class: OpenConext\EngineBlockFunctionalTestingBundle\Fixtures\FunctionalTestingPdpClient
        arguments:
            - '@engineblock.function_testing.data_store.pdp_client'

    engineblock.functional_testing.fixture.authentication_loop_guard:
        class: OpenConext\EngineBlockFunctionalTestingBundle\Fixtures\FunctionalTestingAuthenticationLoopGuard
        arguments:
            - '@engineblock.authentication.authentication_loop_guard'
            - '@engineblock.functional_testing.data_store.authentication_loop_guard'

    engineblock.functional_testing.fixture.attribute_aggregation_client:
        class: OpenConext\EngineBlockFunctionalTestingBundle\Fixtures\FunctionalTestingAttributeAggregationClient
        arguments:
            - '@engineblock.function_testing.data_store.attribute_aggregation_client'
    #endregion Fixtures

    #region Data Stores
    engineblock.functional_testing.data_store.service_registry:
        class: OpenConext\EngineBlockFunctionalTestingBundle\Fixtures\DataStore\SerializedDataStore
        arguments: ['%engineblock.functional_testing.service_registry_data_store.file%']

    engineblock.functional_testing.data_store.features:
        class: OpenConext\EngineBlockFunctionalTestingBundle\Fixtures\DataStore\JsonDataStore
        arguments: ['%engineblock.functional_testing.features_data_store.file%']

    engineblock.function_testing.data_store.pdp_client:
        class: OpenConext\EngineBlockFunctionalTestingBundle\Fixtures\DataStore\JsonDataStore
        arguments: ['%engineblock.functional_testing.pdp_data_store.file%']

    engineblock.functional_testing.data_store.authentication_loop_guard:
        class: OpenConext\EngineBlockFunctionalTestingBundle\Fixtures\DataStore\JsonDataStore
        arguments: ['%engineblock.functional_testing.authentication_loop_guard_data_store.file%']

    engineblock.function_testing.data_store.attribute_aggregation_client:
        class: OpenConext\EngineBlockFunctionalTestingBundle\Fixtures\DataStore\JsonDataStore
        arguments: ['%engineblock.functional_testing.attribute_aggregation_data_store.file%']
    #endregion Data Stores
