imports:
    - { resource: functional_testing.yml }
    - { resource: config_dev.yml }

framework:
    test: ~
    router:
        resource: "%kernel.root_dir%/config/routing_test.yml"
        strict_requirements: true
    profiler:
        collect: false

web_profiler:
    toolbar: false
    intercept_redirects: false
