security:
    providers:
        in_memory:
            memory:
                users:
                    "%api.users.janus.username%":
                        password: "%api.users.janus.password%"
                        roles: 'ROLE_API_USER_JANUS'
                    "%api.users.profile.username%":
                        password: "%api.users.profile.password%"
                        roles: 'ROLE_API_USER_PROFILE'
                    "%api.users.deprovision.username%":
                        password: "%api.users.deprovision.password%"
                        roles: 'ROLE_API_USER_DEPROVISION'

    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|stylesheets|images|js|javascripts)/
            security: false
            stateless: true

        api:
            host: ^engine-api\..+
            http_basic: ~
            entry_point: engineblock.security.http_basic_entry_point
            stateless: true
            pattern: ^/.+

        monitor:
            pattern: ^/(info|health)$
            security: false

        main:
            anonymous: ~
            stateless:  true
