services:
    engineblock.compat.application:
        class: EngineBlock_ApplicationSingleton
        factory:  [EngineBlock_ApplicationSingleton, getInstance]

    engineblock.compat.di_container:
        public: false
        class: EngineBlock_Application_DiContainer
        factory: ["@engineblock.compat.application", getDiContainer]

    engineblock.compat.repository.metadata:
        public: false
        class: OpenConext\EngineBlock\Metadata\MetadataRepository\MetadataRepositoryInterface
        factory: ["@engineblock.compat.di_container", getMetadataRepository]

    engineblock.compat.doctrine.entity_manager:
        public: false
        class: Doctrine\ORM\EntityManager
        factory: ["@engineblock.compat.di_container", getEntityManager]

    engineblock.compat.doctrine.dbal_connection:
        public: false
        class: Doctrine\DBAL\Connection
        factory: ["@engineblock.compat.doctrine.entity_manager", getConnection]

    engineblock.compat.view:
        class: EngineBlock_View
        calls:
            - ['setLayout', ["@engineblock.compat.layout"]]

    engineblock.compat.layout:
        class: Zend_Layout
        calls:
            - ['setLayout',       ["%view_default_layout%"]]
            - ['setLayoutPath',   ["%kernel.root_dir%/Resources/views/layouts/scripts/"]]
            - ['setViewBasePath', ["%kernel.root_dir%/Resources/views/modules/"]]
        properties:
            title: "%view_default_title%"
            header: "%view_default_header%"
            assetVersion: "%asset_version%"

    engineblock.compat.logger:
        class: Monolog\Logger
        factory: [EngineBlock_ApplicationSingleton, getLog]
#    Services that were previously configured and gotten through the DiContainer
    engineblock.compat.xml_converter:
        class: EngineBlock_Corto_XmlToArray

    engineblock.compat.corto_filter_command_factory:
        class: EngineBlock_Corto_Filter_Command_Factory

    engineblock.compat.database_connection_factory:
        class: EngineBlock_Database_ConnectionFactory
        arguments:
            - "@engineblock.compat.doctrine.entity_manager"

    engineblock.compat.corto_model_consent_factory:
        class: EngineBlock_Corto_Model_Consent_Factory
        arguments:
            - "@engineblock.compat.corto_filter_command_factory"
            - "@engineblock.compat.database_connection_factory"

    engineblock.compat.time_provider:
        class: EngineBlock_TimeProvider_Default

    engineblock.compat.saml2_id_generator:
        class: EngineBlock_Saml2_IdGenerator_Default

    engineblock.compat.attribute_release_policy_enforcer:
        public: false
        class: EngineBlock_Arp_AttributeReleasePolicyEnforcer

    engineblock.compat.translator_cache_proxy:
        class: EngineBlock_Translate_CacheProxy
        arguments:
            -
                en: "%kernel.root_dir%/../languages/en.php"
                nl: "%kernel.root_dir%/../languages/nl.php"
            - "@?engineblock.compat.zend.apc_cache"

    engineblock.compat.translator:
        class: Zend_Translate
        factory: ["@engineblock.compat.translator_cache_proxy", "load"]
        calls:
            - ["setLocale", ["@=service('engineblock.locale_provider').getLocale()"]]
