services:
    engineblock.repository.consent:
        public: false
        class: OpenConext\EngineBlockBundle\Authentication\Repository\DbalConsentRepository
        arguments:
            - "@engineblock.compat.doctrine.dbal_connection"

    engineblock.repository.user:
        public: false
        class: OpenConext\EngineBlockBundle\Authentication\Repository\UserRepository
        factory: ["@doctrine.orm.entity_manager", getRepository]
        arguments:
            - 'OpenConext\EngineBlockBundle\Authentication\Entity\User'

    engineblock.repository.service_provider:
        public: false
        class: Doctrine\ORM\EntityRepository
        factory: ["@doctrine.orm.entity_manager", getRepository]
        arguments:
            - 'OpenConext\EngineBlock\Metadata\Entity\ServiceProvider'

    engineblock.repository.identity_provider:
        public: false
        class: Doctrine\ORM\EntityRepository
        factory: ["@doctrine.orm.entity_manager", getRepository]
        arguments:
            - 'OpenConext\EngineBlock\Metadata\Entity\IdentityProvider'