# This routing file is separated due to being hosted on a different sub-domain
# Allowed methods are registered in the controllers, so API specific exceptions are thrown
# see app/config/routing.yml

api_heartbeat:
    path:     /
    defaults:
        _controller: engineblock.controller.api.heartbeat:itWorksAction

api_connections:
    path:     /api/connections
    methods:    [POST]
    defaults:
        _controller: engineblock.controller.api.connections:pushConnectionsAction

api_consent_user:
    path:    /consent/{userId}
    requirements:
        userId: .+
    defaults:
        _controller: engineblock.controller.api.consent:userAction

api_metadata_idp:
    path:    /metadata/idp
    methods: [GET]
    defaults:
        _controller: engineblock.controller.api.metadata:idpAction

api_attribute_release_policy:
    path:   /arp
    methods: [POST]
    defaults:
        _controller: engineblock.controller.api.attribute_release_policy:applyArpAction
