# This routing file is separated due to being hosted on a different sub-domain
# see app/config/routing.yml
# Allowed methods are registered in the controllers so API specific exceptions are thrown

api_heartbeat:
    path:     /
    defaults:
        _controller: engineblock.controller.api.heartbeat:itWorksAction

api_connections:
    path:     /api/connections
    defaults:
        _controller: engineblock.controller.api.connections:pushConnectionsAction

api_consent_user:
    path:    /consent/{userId}
    requirements:
        userId: .+
    defaults:
        _controller: engineblock.controller.api.consent:userAction

api_deprovision_delete_user_data_dry_run:
    path:    /deprovision/{collabPersonId}/dry-run
    requirements:
        collabPersonId: .+
    defaults:
        _controller: engineblock.controller.api.deprovision:dryRunAction

api_deprovision_get_user_data:
    path:    /deprovision/{collabPersonId}
    requirements:
        collabPersonId: .+
    defaults:
        _controller: engineblock.controller.api.deprovision:userDataAction

api_metadata_idp:
    path:    /metadata/idp
    defaults:
        _controller: engineblock.controller.api.metadata:idpAction

api_apply_attribute_release_policy:
    path:   /arp
    defaults:
        _controller: engineblock.controller.api.attribute_release_policy:applyArpAction

api_read_attribute_release_policy:
    path:   /read-arp
    defaults:
        _controller: engineblock.controller.api.attribute_release_policy:readArpAction
