# This routing file is separated due to being hosted on a different sub-domain
# see app/config/routing.yml

api_heartbeat:
    path:     /
    defaults:
        _controller: engineblock.controller.api.heartbeat:itWorksAction

api_connections:
    path:     /api/connections
    methods:    [POST]
    defaults:
        _controller: engineblock.controller.api.connections:pushConnectionsAction

api_consent_user:
    path:    /consent/{userId}
    methods: [GET]
    requirements:
        userId: .+
    defaults:
        _controller: engineblock.controller.api.consent:userAction

api_metadata_idp:
    path:    /metadata/idp
    methods: [GET]
    defaults:
        _controller: engineblock.controller.api.metadata:idpAction
