# This routing file is separated due to being hosted on a different sub-domain
# see app/config/routing.yml
# Allowed methods are registered in the controllers so API specific exceptions are thrown

api_heartbeat:
    path:     /
    defaults:
        _controller: engineblock.controller.api.heartbeat:itWorksAction
        _format: json

api_connections:
    path:     /api/connections
    defaults:
        _controller: engineblock.controller.api.connections:pushConnectionsAction
        _format: json

api_consent_user:
    path:    /consent/{userId}
    requirements:
        userId: .+
    defaults:
        _controller: engineblock.controller.api.consent:userAction
        _format: json

api_remove_consent_user:
    path:    /remove-consent
    defaults:
        _controller: engineblock.controller.api.deprovision:removeAction
        _format: json

api_deprovision_delete_user_data_dry_run:
    path:    /deprovision/{collabPersonId}/dry-run
    requirements:
        collabPersonId: .+
    defaults:
        _controller: engineblock.controller.api.deprovision:dryRunAction
        _format: json

api_deprovision_get_user_data:
    path:    /deprovision/{collabPersonId}
    requirements:
        collabPersonId: .+
    defaults:
        _controller: engineblock.controller.api.deprovision:userDataAction
        _format: json

api_metadata_idp:
    path:    /metadata/idp
    defaults:
        _controller: engineblock.controller.api.metadata:idpAction
        _format: json

api_apply_attribute_release_policy:
    path:   /arp
    defaults:
        _controller: engineblock.controller.api.attribute_release_policy:applyArpAction
        _format: json

api_read_attribute_release_policy:
    path:   /read-arp
    defaults:
        _controller: engineblock.controller.api.attribute_release_policy:readArpAction
        _format: json
