### Idp

metadata_idp:
    path:       '/authentication/idp/metadata'
    methods:    [GET]
    defaults:
        _controller: engineblock.controller.authentication.metadata:idpMetadataAction
        virtualOrganization: ~
        keyId: ~

metadata_idp_vo:
    path:       '/authentication/idp/metadata/vo:{virtualOrganization}'
    methods:    [GET]
    defaults:
        _controller: engineblock.controller.authentication.metadata:idpMetadataAction
        keyId: ~
    requirements:
        virtualOrganization: .+

metadata_idp_vo_key:
    path:       '/authentication/idp/metadata/vo:{virtualOrganization}/key:{keyId}'
    methods:    [GET]
    defaults:
        _controller: engineblock.controller.authentication.metadata:idpMetadataAction
    requirements:
        virtualOrganization: .+
        keyId: .+

metadata_idp_key:
    path:       '/authentication/idp/metadata/key:{keyId}'
    methods:    [GET]
    defaults:
        _controller: engineblock.controller.authentication.metadata:idpMetadataAction
        virtualOrganization: ~
    requirements:
        keyId: .+

metadata_idp_key_vo:
    path:       '/authentication/idp/metadata/key:{keyId}/vo:{virtualOrganization}'
    methods:    [GET]
    defaults:
        _controller: engineblock.controller.authentication.metadata:idpMetadataAction
    requirements:
        keyId: .+
        virtualOrganization: .+

### Sp

metadata_sp:
    path:       '/authentication/sp/metadata'
    methods:    [GET]
    defaults:
        _controller: engineblock.controller.authentication.metadata:spMetadataAction
        virtualOrganization: ~
        keyId: ~

metadata_sp_vo:
    path:       '/authentication/sp/metadata/vo:{virtualOrganization}'
    methods:    [GET]
    defaults:
        _controller: engineblock.controller.authentication.metadata:spMetadataAction
        keyId: ~
    requirements:
        virtualOrganization: .+

metadata_sp_vo_key:
    path:       '/authentication/sp/metadata/vo:{virtualOrganization}/key:{keyId}'
    methods:    [GET]
    defaults:
        _controller: engineblock.controller.authentication.metadata:spMetadataAction
    requirements:
        virtualOrganization: .+
        keyId: .+

metadata_sp_key:
    path:       '/authentication/sp/metadata/key:{keyId}'
    methods:    [GET]
    defaults:
        _controller: engineblock.controller.authentication.metadata:spMetadataAction
        virtualOrganization: ~
    requirements:
        keyId: .+

metadata_sp_key_vo:
    path:       '/authentication/sp/metadata/key:{keyId}/vo:{virtualOrganization}'
    methods:    [GET]
    defaults:
        _controller: engineblock.controller.authentication.metadata:spMetadataAction
    requirements:
        keyId: .+
        virtualOrganization: .+

### IdPs
metadata_all_idps:
    path:       '/authentication/proxy/idps-metadata'
    methods:    [GET]
    defaults:
        _controller: engineblock.controller.authentication.metadata:allIdpsMetadataAction
        virtualOrganization: ~
        keyId: ~

metadata_all_idps_vo:
    path:       '/authentication/proxy/idps-metadata/vo:{virtualOrganization}'
    methods:    [GET]
    defaults:
        _controller: engineblock.controller.authentication.metadata:allIdpsMetadataAction
        keyId: ~
    requirements:
        virtualOrganization: .+

metadata_all_idps_vo_key:
    path:       '/authentication/proxy/idps-metadata/vo:{virtualOrganization}/key:{keyId}'
    methods:    [GET]
    defaults:
        _controller: engineblock.controller.authentication.metadata:allIdpsMetadataAction
    requirements:
        virtualOrganization: .+
        keyId: .+

metadata_all_idps_key:
    path:       '/authentication/proxy/idps-metadata/key:{keyId}'
    methods:    [GET]
    defaults:
        _controller: engineblock.controller.authentication.metadata:allIdpsMetadataAction
        virtualOrganization: ~
    requirements:
        keyId: .+

metadata_all_idps_key_vo:
    path:       '/authentication/proxy/idps-metadata/key:{keyId}/vo:{virtualOrganization}'
    methods:    [GET]
    defaults:
        _controller: engineblock.controller.authentication.metadata:allIdpsMetadataAction
    requirements:
        keyId: .+
        virtualOrganization: .+

### Edugain
metadata_edugain:
    path:       '/authentication/proxy/edugain-metadata'
    methods:    [GET]
    defaults:
        _controller: engineblock.controller.authentication.metadata:edugainMetadataAction
        keyId: ~

metadata_edugain_key:
    path:       '/authentication/proxy/edugain-metadata/key:{keyId}'
    methods:    [GET]
    defaults:
        _controller: engineblock.controller.authentication.metadata:edugainMetadataAction
    requirements:
        keyId: .+
