services:
    engineblock.controller.authentication.service_provider:
        class: OpenConext\EngineBlock\AuthenticationBundle\Controller\ServiceProviderController
        arguments:
            - @eb.compat.application
            - @eb.compat.view

    engineblock.controller.authentication.identity_provider:
        class: OpenConext\EngineBlock\AuthenticationBundle\Controller\IdentityProviderController
        arguments:
            - @eb.compat.application
            - @eb.compat.view
            - @eb.compat.logger
            - @engineblock.service.request_access_mailer

    engineblock.controller.authentication.index:
        class: OpenConext\EngineBlock\AuthenticationBundle\Controller\IndexController
        arguments:
            - @eb.compat.application
            - @eb.compat.view

    engineblock.controller.authentication.feedback:
        class: OpenConext\EngineBlock\AuthenticationBundle\Controller\FeedbackController
        arguments:
            - @eb.compat.application
            - @eb.compat.view
            - @eb.compat.logger

    engineblock.controller.authentication.metadata:
        class: OpenConext\EngineBlock\AuthenticationBundle\Controller\MetadataController
        arguments:
            - @eb.compat.application
            - @eb.compat.view

    engineblock.controller.authentication.certificate:
        class: OpenConext\EngineBlock\AuthenticationBundle\Controller\CertificateController
        arguments:
            - @eb.compat.application

    engineblock.controller.authentication.debug:
        class: OpenConext\EngineBlock\AuthenticationBundle\Controller\DebugController
        arguments:
            - @eb.compat.application

    engineblock.controller.authentication.wayf:
        class: OpenConext\EngineBlock\AuthenticationBundle\Controller\WayfController
        arguments:
            - @eb.compat.application
            - @eb.compat.view

    engineblock.controller.authentication.proxy:
        class: OpenConext\EngineBlock\AuthenticationBundle\Controller\ProxyController
        arguments:
            - @eb.compat.application

    engineblock.service.request_access_mailer:
        class: OpenConext\EngineBlock\AuthenticationBundle\Service\RequestAccessMailer
        arguments:
            - @eb.bridge.mailer
