services:
    engineblock.listener.single_sign_on_exception:
        class: OpenConext\EngineBlock\AuthenticationBundle\EventListener\RedirectToFeedbackPageExceptionListener
        tags:
            - { name: kernel.event_listener, event: kernel.exception, method: onKernelException }
        arguments:
            - @eb.compat.application
            - @router
            - @eb.bridge.error_reporter
            - @eb.compat.logger

    engineblock.listener.not_found_http_exception:
        class: OpenConext\EngineBlock\AuthenticationBundle\EventListener\NotFoundHttpListener
        tags:
            - { name: kernel.event_listener, event: kernel.exception, method: onKernelException }
        arguments:
            - @eb.compat.application
            - @eb.compat.view
            - @eb.compat.logger
