open_conext_engine_block_authentication_homepage:
    path:     /
    defaults: { _controller: engineblock.controller.authentication.index:indexAction }

authentication_sp_debug:
    path:       /authentication/sp/debug
    methods:    [GET]
    defaults:
        _controller: engineblock.controller.authentication.debug:debugSpConnectionAction

identity_provider:
    resource: routing/identity_provider.yml

service_provider:
    resource: routing/service_provider.yml

metadata:
    resource: routing/metadata.yml

certificate:
    resource: routing/certificate.yml

feedback:
    resource: routing/feedback.yml
    prefix:   '/authentication/feedback'
