---

version: "3.8"

services:
    openconext:
        image: ghcr.io/openconext/openconext-containers/openconext-php-build-eb:latest
        volumes:
            - ../:/home/runner/work/OpenConext-engineblock
        working_dir: /home/runner/work/OpenConext-engineblock
        environment:
            - PHPFPM_PORT=9000
