services:
    openconext.api.controller.connections:
        class: OpenConext\EngineBlock\ApiBundle\Controller\ConnectionsController
        arguments:
            - @eb.compat.application
            - @security.authorization_checker
            - @api.service.features

    openconext.api.controller.consent:
        class: OpenConext\EngineBlock\ApiBundle\Controller\ConsentController
        arguments:
            - @api.service.consent
            - @api.service.features
            - @security.authorization_checker

    openconext.api.controller.heartbeat:
        class: OpenConext\EngineBlock\ApiBundle\Controller\HeartbeatController
