services:
    openconext.api.controller.connections:
        class: OpenConext\EngineBlock\ApiBundle\Controller\ConnectionsController
        arguments:
            - @eb.compat.application
            - @security.authorization_checker
            - @api.service.features

    openconext.api.controller.heartbeat:
        class: OpenConext\EngineBlock\ApiBundle\Controller\HeartbeatController
