api_heartbeat:
    path:     /
    defaults:
        _controller: openconext.api.controller.heartbeat:itWorksAction

api_connections:
    path:     /api/connections
    methods:    [POST]
    defaults:
        _controller: openconext.api.controller.connections:pushConnectionsAction

api_consent_user:
    path:    /api/consent/{userId}
    methods: [GET]
    requirements:
        userId: .+
    defaults:
        _controller: openconext.api.controller.consent:userAction
