services:
    api.security.http_basic_entry_point:
        class: OpenConext\EngineBlock\ApiBundle\Security\Http\EntryPoint\JsonBasicAuthenticationEntryPoint
        arguments:
            - "engine-api.%domain%"

    api.service.features:
        class: OpenConext\EngineBlock\ApiBundle\Service\FeaturesService
        arguments:
            - %api.features.metadata_push.enabled%
            - %api.features.consent_listing.enabled%
            - %api.features.metadata_api.enabled%

    api.service.consent:
        class: OpenConext\EngineBlock\ApiBundle\Service\ConsentService
        arguments:
            - @engineblock.repository.consent
            - @api.service.metadata
            - @eb.compat.logger

    api.service.metadata:
        class: OpenConext\EngineBlock\ApiBundle\Service\MetadataService
        arguments:
            - @eb.compat.repository.metadata
            - @eb.compat.logger
