services:
    api.security.http_basic_entry_point:
        class: OpenConext\EngineBlock\ApiBundle\Security\Http\EntryPoint\JsonBasicAuthenticationEntryPoint
        arguments:
            - "engine-api.%domain%"
