services:
    engineblock.functional_test.controller.identity_provider:
        class: OpenConext\EngineBlock\FunctionalTestingBundle\Controllers\IdentityProviderController
        arguments:
            - "@engineblock.mock_entities.idp_registry"
            - "@engineblock.mock_entities.saml_response_factory"

    engineblock.functional_test.controller.service_provider:
        class: OpenConext\EngineBlock\FunctionalTestingBundle\Controllers\ServiceProviderController
        arguments:
            - "@engineblock.mock_entities.sp_registry"
            - "@engineblock.functional_testing.service.engine_block"
