services:
    engineblock.mock_entities.idp_factory:
        class: OpenConext\EngineBlock\FunctionalTestingBundle\Mock\MockIdentityProviderFactory
        arguments: ['@router']

    engineblock.mock_entities.sp_factory:
        class: OpenConext\EngineBlock\FunctionalTestingBundle\Mock\MockServiceProviderFactory
        arguments: ['@router']

    engineblock.mock_entities.idp_registry:
        class: OpenConext\EngineBlock\FunctionalTestingBundle\Mock\EntityRegistry
        arguments: ['@engineblock.mock_entities.data_store.mock_idps']

    engineblock.mock_entities.sp_registry:
        class: OpenConext\EngineBlock\FunctionalTestingBundle\Mock\EntityRegistry
        arguments: ['@engineblock.mock_entities.data_store.mock_sps']

    engineblock.mock_entities.saml_response_factory:
        class: OpenConext\EngineBlock\FunctionalTestingBundle\Saml2\ResponseFactory

    engineblock.mock_entities.data_store.mock_idps:
        class: OpenConext\Component\EngineBlockFixtures\DataStore\SerializedDataStore
        arguments: ['%idp_fixture_file%']

    engineblock.mock_entities.data_store.mock_sps:
        class: OpenConext\Component\EngineBlockFixtures\DataStore\SerializedDataStore
        arguments: ['%sp_fixture_file%']
