profile_homepage:
    path:     /
    defaults:
        _controller: profile.controller.index:indexAction

profile_delete_user:
    path:       /profile/delete-user
    methods:    [GET,POST]
    defaults:
        _controller: profile.controller.delete_user:indexAction

profile_delete_user_success:
    path:       /profile/delete-user/success
    methods:    [GET]
    defaults:
        _controller: profile.controller.delete_user:successAction
