services:
    eb.compat.event_listener.not_found_http_exception:
        class: OpenConext\EngineBlock\CompatibilityBundle\EventListener\NotFoundHttpListener
        tags:
            - { name: kernel.event_listener, event: kernel.exception, method: onKernelException, priority: 25 }
        arguments:
            - @eb.compat.application
            - @eb.compat.view
            - @eb.compat.logger

    eb.compat.event_listener.fallback_exception:
        class: OpenConext\EngineBlock\CompatibilityBundle\EventListener\FallbackExceptionListener
        tags:
            - { name: kernel.event_listener, event: kernel.exception, method: onKernelException, priority: -200 }
        arguments:
            - @eb.compat.application
            - @eb.compat.view
            - @eb.compat.logger
            - @eb.bridge.error_reporter
