### IdP

certificate_idp:
    path:       '/authentication/idp/certificate'
    methods:    [GET]
    defaults:
        _controller: engineblock.controller.authentication.certificate:idpSigningCertificateAction
        keyId: ~

certificate_idp_key:
    path:       '/authentication/idp/certificate/key:{keyId}'
    methods:    [GET]
    defaults:
        _controller: engineblock.controller.authentication.certificate:idpSigningCertificateAction
    requirements:
        keyId: .+

## Sp

certificate_sp:
    path:       '/authentication/sp/certificate'
    methods:    [GET]
    defaults:
        _controller: engineblock.controller.authentication.certificate:spSigningCertificateAction
        keyId: ~

certificate_sp_key:
    path:       '/authentication/sp/certificate/key:{keyId}'
    methods:    [GET]
    defaults:
        _controller: engineblock.controller.authentication.certificate:spSigningCertificateAction
    requirements:
        keyId: .+
