authentication_sp_consume_assertion:
    path:     /authentication/sp/consume-assertion
    methods:  [GET,POST] # GET is allowed on purpose to present a meaningful error message.
    defaults:
        _controller: engineblock.controller.authentication.service_provider:consumeAssertionAction

authentication_sp_process_consent:
    path:     /authentication/sp/process-consent
    methods:  [GET,POST]
    defaults:
        _controller: engineblock.controller.authentication.service_provider:processConsentAction
