monolog:
    channels: ["%logger.channel%", "authentication"]
    handlers:
        main:
            type: fingers_crossed
            activation_strategy: engineblock.logger.manual_or_error_activation_strategy
            passthru_level: "%logger.fingers_crossed.passthru_level%"
            channels:  [!authentication]
            handler: stderr
        authentication:
            type:      stream
            path:      php://stderr
            level:     INFO
            channels:  [authentication]
            formatter: engineblock.logger.formatter.syslog_json
        stderr:
            type:      stream
            path:      php://stderr
            formatter: engineblock.logger.formatter.syslog_json
