name: visual-regression
on:
    pull_request:
    push:
        tags:
            - '[0-9]+.[0-9]+.[0-9]+*'
    # run at 6 hour UTC
    schedule:
      - cron: "0 6 * * *"
jobs:
    build:
        runs-on: ubuntu-latest
        timeout-minutes: 30
        env:
          PROD_PHP: php72
          DOCKER_COMPOSE:  docker-compose -f docker-compose.yml -f docker-compose-${{matrix.php}}.yml
        container:
            image: cypress/browsers:node12.16.1-chrome80-ff73
            options: --user 1001
        steps:
            - name: Checkout
              uses: actions/checkout@master
            - name: Init environment
              run: cd docker && ./init.sh && cat .env
            - name: Build Docker environmnent
              if: always()
              run: |
                cd docker &&
                ${DOCKER_COMPOSE} up -d --build &&
                docker-compose exec -T php-fpm.vm.openconext.org bash -c '
                    SYMFONY_ENV=ci composer install --prefer-dist -n -o && \
                    ./app/console cache:clear --env=ci && \
                    cd theme && npm ci && npm run build
                '
            - uses: actions/checkout@v1
            - uses: cypress-io/github-action@v2
              with:
                  browser: firefox
              env:
                  SYMFONY_ENV: ci
